name: weather
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  dio: ^5.9.2
  firebase_core: ^4.10.0
  firebase_crashlytics: ^5.2.3
  firebase_messaging: ^16.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_local_notifications: ^22.0.0
  geolocator: ^14.0.2
  get: ^4.7.3
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
